name: SmartSpawner
version: '${version}'
main: github.nighter.smartspawner.SmartSpawner
api-version: '1.21'
authors: [ https://github.com/ptthanh02/Smart-Spawner/graphs/contributors ]
folia-supported: true
softdepend:
  # Bedrock Support Plugins
  - floodgate
  - Geyser-Spigot

  # Shop Plugins
  - EconomyShopGUI
  - EconomyShopGUI-Premium
  - ShopGUIPlus
  - zShop
  - ExcellentShop

  # Utility/Economy Plugins
  - CoinEngine
  - Vault

  # Protection/Region Plugins
  - WorldGuard
  - GriefPrevention
  - Lands
  - Towny
  - SimpleClaimSystem
  - RedProtect
  - MinePlots
  - PlotSquared
  - Residence

  # World Management Plugins
  - Multiverse-Core
  - MultiWorld
  - Worlds
  - SuperiorSkyblock2
  - Bentobox
  - IridiumSkyblock

  # RPG/Skill Plugins
  - AuraSkills

  #Drops Plugins
  - MythicMobs

commands:
  smartspawner:
    description: Main command for SmartSpawner plugin
    usage: /smartspawner [reload|give|list|hologram|prices|clear] [args...]
    aliases: [ ss, spawner ]
    permission: smartspawner.command.use
    permission-message: "You don't have permission to use SmartSpawner commands!"

permissions:
  # Main command permission
  smartspawner.command.use:
    description: Allow access to SmartSpawner commands
    default: op

  # Subcommand permissions
  smartspawner.command.reload:
    description: Permission to reload SmartSpawner plugin
    default: op

  smartspawner.command.give:
    description: Allow giving spawners to yourself
    default: op

  smartspawner.command.list:
    description: Allow viewing list of spawners and teleporting to them
    default: op

  smartspawner.command.hologram:
    description: Allow toggling hologram for spawners
    default: op

  smartspawner.command.prices:
    description: Allow viewing sell prices of spawner items
    default: true

  smartspawner.command.clear:
    description: Allow clearing holograms and ghost spawners
    default: op

  # Legacy permissions (for backwards compatibility)
  smartspawner.admin:
    description: Legacy permission for SmartSpawner commands
    default: op
    children:
      smartspawner.command.use: true

  smartspawner.reload:
    description: Legacy permission for reload command
    default: op
    children:
      smartspawner.command.reload: true

  smartspawner.give:
    description: Legacy permission for give command
    default: op
    children:
      smartspawner.command.give: true

  smartspawner.list:
    description: Legacy permission for list command
    default: op
    children:
      smartspawner.command.list: true

  smartspawner.hologram:
    description: Legacy permission for hologram command
    default: op
    children:
      smartspawner.command.hologram: true

  smartspawner.prices:
    description: Legacy permission for prices command
    default: true
    children:
      smartspawner.command.prices: true

  # Feature permissions
  smartspawner.changetype:
    description: Allow changing spawner type with spawn egg
    default: op

  smartspawner.stack:
    description: Allow stacking spawners
    default: true

  smartspawner.break:
    description: Allow breaking spawners
    default: true

  smartspawner.sellall:
    description: Allow selling items in spawner storage GUI
    default: true

  smartspawner.limits.bypass:
    description: Bypass spawner limits per chunk
    default: false
